export type Province = { id: string; th: string; en: string };

export const PROVINCES: Province[] = [
  { id: "bangkok", th: "กรุงเทพมหานคร", en: "Bangkok" },
  { id: "krabi", th: "กระบี่", en: "Krabi" },
  { id: "kanchanaburi", th: "กาญจนบุรี", en: "Kanchanaburi" },
  { id: "kalasin", th: "กาฬสินธุ์", en: "Kalasin" },
  { id: "kamphaeng-phet", th: "กำแพงเพชร", en: "Kamphaeng Phet" },
  { id: "khon-kaen", th: "ขอนแก่น", en: "Khon Kaen" },
  { id: "chanthaburi", th: "จันทบุรี", en: "Chanthaburi" },
  { id: "chachoengsao", th: "ฉะเชิงเทรา", en: "Chachoengsao" },
  { id: "chonburi", th: "ชลบุรี", en: "Chonburi" },
  { id: "chainat", th: "ชัยนาท", en: "Chai Nat" },
  { id: "chaiyaphum", th: "ชัยภูมิ", en: "Chaiyaphum" },
  { id: "chumphon", th: "ชุมพร", en: "Chumphon" },
  { id: "chiang-rai", th: "เชียงราย", en: "Chiang Rai" },
  { id: "chiang-mai", th: "เชียงใหม่", en: "Chiang Mai" },
  { id: "trang", th: "ตรัง", en: "Trang" },
  { id: "trat", th: "ตราด", en: "Trat" },
  { id: "tak", th: "ตาก", en: "Tak" },
  { id: "nakhon-nayok", th: "นครนายก", en: "Nakhon Nayok" },
  { id: "nakhon-pathom", th: "นครปฐม", en: "Nakhon Pathom" },
  { id: "nakhon-phanom", th: "นครพนม", en: "Nakhon Phanom" },
  { id: "nakhon-ratchasima", th: "นครราชสีมา", en: "Nakhon Ratchasima" },
  { id: "nakhon-si-thammarat", th: "นครศรีธรรมราช", en: "Nakhon Si Thammarat" },
  { id: "nakhon-sawan", th: "นครสวรรค์", en: "Nakhon Sawan" },
  { id: "nonthaburi", th: "นนทบุรี", en: "Nonthaburi" },
  { id: "narathiwat", th: "นราธิวาส", en: "Narathiwat" },
  { id: "nan", th: "น่าน", en: "Nan" },
  { id: "bueng-kan", th: "บึงกาฬ", en: "Bueng Kan" },
  { id: "buriram", th: "บุรีรัมย์", en: "Buriram" },
  { id: "pathum-thani", th: "ปทุมธานี", en: "Pathum Thani" },
  { id: "prachuap-khiri-khan", th: "ประจวบคีรีขันธ์", en: "Prachuap Khiri Khan" },
  { id: "prachinburi", th: "ปราจีนบุรี", en: "Prachinburi" },
  { id: "pattani", th: "ปัตตานี", en: "Pattani" },
  { id: "ayutthaya", th: "พระนครศรีอยุธยา", en: "Phra Nakhon Si Ayutthaya" },
  { id: "phang-nga", th: "พังงา", en: "Phang Nga" },
  { id: "phatthalung", th: "พัทลุง", en: "Phatthalung" },
  { id: "phichit", th: "พิจิตร", en: "Phichit" },
  { id: "phitsanulok", th: "พิษณุโลก", en: "Phitsanulok" },
  { id: "phetchaburi", th: "เพชรบุรี", en: "Phetchaburi" },
  { id: "phetchabun", th: "เพชรบูรณ์", en: "Phetchabun" },
  { id: "phrae", th: "แพร่", en: "Phrae" },
  { id: "phayao", th: "พะเยา", en: "Phayao" },
  { id: "phuket", th: "ภูเก็ต", en: "Phuket" },
  { id: "maha-sarakham", th: "มหาสารคาม", en: "Maha Sarakham" },
  { id: "mukdahan", th: "มุกดาหาร", en: "Mukdahan" },
  { id: "mae-hong-son", th: "แม่ฮ่องสอน", en: "Mae Hong Son" },
  { id: "yasothon", th: "ยโสธร", en: "Yasothon" },
  { id: "yala", th: "ยะลา", en: "Yala" },
  { id: "roi-et", th: "ร้อยเอ็ด", en: "Roi Et" },
  { id: "ranong", th: "ระนอง", en: "Ranong" },
  { id: "rayong", th: "ระยอง", en: "Rayong" },
  { id: "ratchaburi", th: "ราชบุรี", en: "Ratchaburi" },
  { id: "lopburi", th: "ลพบุรี", en: "Lopburi" },
  { id: "lampang", th: "ลำปาง", en: "Lampang" },
  { id: "lamphun", th: "ลำพูน", en: "Lamphun" },
  { id: "loei", th: "เลย", en: "Loei" },
  { id: "sisaket", th: "ศรีสะเกษ", en: "Sisaket" },
  { id: "sakon-nakhon", th: "สกลนคร", en: "Sakon Nakhon" },
  { id: "songkhla", th: "สงขลา", en: "Songkhla" },
  { id: "satun", th: "สตูล", en: "Satun" },
  { id: "samut-prakan", th: "สมุทรปราการ", en: "Samut Prakan" },
  { id: "samut-songkhram", th: "สมุทรสงคราม", en: "Samut Songkhram" },
  { id: "samut-sakhon", th: "สมุทรสาคร", en: "Samut Sakhon" },
  { id: "sa-kaeo", th: "สระแก้ว", en: "Sa Kaeo" },
  { id: "saraburi", th: "สระบุรี", en: "Saraburi" },
  { id: "sing-buri", th: "สิงห์บุรี", en: "Sing Buri" },
  { id: "sukhothai", th: "สุโขทัย", en: "Sukhothai" },
  { id: "suphan-buri", th: "สุพรรณบุรี", en: "Suphan Buri" },
  { id: "surat-thani", th: "สุราษฎร์ธานี", en: "Surat Thani" },
  { id: "surin", th: "สุรินทร์", en: "Surin" },
  { id: "nong-khai", th: "หนองคาย", en: "Nong Khai" },
  { id: "nong-bua-lamphu", th: "หนองบัวลำภู", en: "Nong Bua Lamphu" },
  { id: "ang-thong", th: "อ่างทอง", en: "Ang Thong" },
  { id: "amnatcharoen", th: "อำนาจเจริญ", en: "Amnat Charoen" },
  { id: "udon-thani", th: "อุดรธานี", en: "Udon Thani" },
  { id: "uttaradit", th: "อุตรดิตถ์", en: "Uttaradit" },
  { id: "uthai-thani", th: "อุทัยธานี", en: "Uthai Thani" },
  { id: "ubon-ratchathani", th: "อุบลราชธานี", en: "Ubon Ratchathani" },
];

export function provinceName(id: string, locale: string) {
  const found = PROVINCES.find((p) => p.id === id);
  if (!found) return id;
  return locale === "en" ? found.en : found.th;
}
